export const GAME_STATES = {
    BOOT: 'BOOT',
    FACTION_SELECT: 'FACTION_SELECT',
    DIFFICULTY_SELECT: 'DIFFICULTY_SELECT',
    MAIN_GAME: 'MAIN_GAME',
    DEBRIEF: 'DEBRIEF',
    LEADERBOARD: 'LEADERBOARD'
};

export const ACTIONS = {
    SELECT_FACTION: 'SELECT_FACTION',
    SELECT_DIFFICULTY: 'SELECT_DIFFICULTY',
    START_GAME: 'START_GAME',
    PAUSE_GAME: 'PAUSE_GAME',
    RESUME_GAME: 'RESUME_GAME',
    SPAWN_THREAT: 'SPAWN_THREAT',
    REMOVE_THREAT: 'REMOVE_THREAT',
    SELECT_THREAT: 'SELECT_THREAT',
    DESELECT_THREAT: 'DESELECT_THREAT',
    SELECT_SYSTEM: 'SELECT_SYSTEM',
    FIRE_INTERCEPTOR: 'FIRE_INTERCEPTOR',
    INTERCEPT_SUCCESS: 'INTERCEPT_SUCCESS',
    INTERCEPT_FAILURE: 'INTERCEPT_FAILURE',
    THREAT_BREACH: 'THREAT_BREACH',
    UPDATE_BATTERY_STATUS: 'UPDATE_BATTERY_STATUS',
    TOGGLE_ECM: 'TOGGLE_ECM',
    ECM_TICK: 'ECM_TICK',
    ECM_COOLDOWN_TICK: 'ECM_COOLDOWN_TICK',
    UPDATE_ASSET_HP: 'UPDATE_ASSET_HP',
    NEXT_WAVE: 'NEXT_WAVE',
    WAVE_PAUSE_TICK: 'WAVE_PAUSE_TICK',
    ADD_LOG_ENTRY: 'ADD_LOG_ENTRY',
    UPDATE_BDA: 'UPDATE_BDA',
    SET_ZOOM: 'SET_ZOOM',
    TOGGLE_AUTO_ENGAGE: 'TOGGLE_AUTO_ENGAGE',
    REQUEST_SUPPORT: 'REQUEST_SUPPORT',
    SUPPORT_FIRE: 'SUPPORT_FIRE',
    ABORT_INTERCEPT: 'ABORT_INTERCEPT',
    PRIORITIZE_THREAT: 'PRIORITIZE_THREAT',
    IGNORE_THREAT: 'IGNORE_THREAT',
    REORDER_QUEUE: 'REORDER_QUEUE',
    TOGGLE_MUTE: 'TOGGLE_MUTE',
    END_GAME: 'END_GAME',
    TICK_TIMERS: 'TICK_TIMERS', // For ECM, Support, and Reloads
    UPDATE_THREAT_POSITIONS: 'UPDATE_THREAT_POSITIONS',
    UPDATE_INTERCEPTIONS: 'UPDATE_INTERCEPTIONS',
    WAVE_TIMER_TICK: 'WAVE_TIMER_TICK'
};

export const KEYBINDINGS = {
    FIRE: ' ',
    CYCLE_NEXT: 'Tab',
    CYCLE_PREV: 'Shift+Tab',
    SELECT_TIER_1: '1',
    SELECT_TIER_2: '2',
    SELECT_TIER_3: '3',
    SELECT_TIER_4: '4',
    TOGGLE_ECM: 'e',
    TOGGLE_PAUSE: 'p',
    REQUEST_SUPPORT: 'r',
    DESELECT: 'Escape',
    ABORT: 'f',
    TOGGLE_QUEUE: 'q',
    TOGGLE_LOG: 'l',
    TOGGLE_BDA: 'b',
    TOGGLE_MUTE: 'm',
    ZOOM_IN: '+',
    ZOOM_OUT: '-',
    TOGGLE_HUD: 'h',
    TOGGLE_DEBUG: 'Control+d'
};

export const DIFFICULTIES = {
    PEACETIME: { id: 'PEACETIME', spawnMultiplier: 0.5, speedMultiplier: 0.8, reloadGrace: 1.5, startHP: 150 },
    ELEVATED: { id: 'ELEVATED', spawnMultiplier: 1.0, speedMultiplier: 1.0, reloadGrace: 1.0, startHP: 100 },
    CRISIS: { id: 'CRISIS', spawnMultiplier: 1.5, speedMultiplier: 1.25, reloadGrace: 0.8, startHP: 80 },
    WAR: { id: 'WAR', spawnMultiplier: 2.0, speedMultiplier: 1.5, reloadGrace: 0.5, startHP: 50 },
};

export const SYSTEM_TIERS = {
    LONG: 'LONG',
    MID: 'MID',
    SHORT: 'SHORT',
    POINT: 'POINT'
};
