export const SYSTEM_STATUS = {
    READY: 'READY',
    ENGAGING: 'ENGAGING',
    RELOADING: 'RELOADING',
    DEGRADED: 'DEGRADED',
    WINCHESTER: 'WINCHESTER'
};

export const THREAT_CONFIDENCE = {
    SURE: 'SURE',
    PROBABLE: 'PROBABLE',
    UNKNOWN: 'UNKNOWN'
};

export const TARGET_CLASSES = {
    BALLISTIC: 'BALLISTIC',
    CRUISE: 'CRUISE',
    HYPERSONIC: 'HYPERSONIC',
    FIGHTER: 'FIGHTER',
    DRONE: 'DRONE',
    BOMB: 'BOMB',
    LASER: 'LASER',
    DIRECTED_ENERGY: 'DIRECTED_ENERGY',
    LOITERING: 'LOITERING',
    ASBM: 'ASBM'
};
